import { BotCommand } from '../commands';
import { Province, City, Scene, BlitzResponse, ISceneText } from './models';

export const LEAVE_BLANK =  'Leave Blank';

const DEFAULT_WRONG_VALUE = `Please choose value from list`;
const DEFAULT_INLINE_OMITTED = `Please choose <b>${BlitzResponse.Yes}</b> or <b>${BlitzResponse.No}</b> using buttons above`;

export const SCENE_TO_VALIDATOR_MAPPER: Record<Scene, {
  REG_EXP_PATTERN?: RegExp,
  ERROR_MESSAGE: {
    WRONG_VALUE: string;
    INLINE_OMITTED?: string;
    MAX_CANT_BE_LESS_THAN_MIN?: string;
  },
}> = {
  [Scene.Province]: {
    ERROR_MESSAGE: {
      WRONG_VALUE: DEFAULT_WRONG_VALUE,
    },
  },
  [Scene.City]: {
    ERROR_MESSAGE: {
      WRONG_VALUE: DEFAULT_WRONG_VALUE,
      INLINE_OMITTED: DEFAULT_INLINE_OMITTED,
    },
  },
  [Scene.Area]: {
    REG_EXP_PATTERN: /^[1-9]\d{0,2}$/,
    ERROR_MESSAGE: {
      WRONG_VALUE: `Please specify value from <b>1</b> to <b>999</b>`,
      MAX_CANT_BE_LESS_THAN_MIN: `Max <b>Area m²</b> can't be less that min!`,
      INLINE_OMITTED: DEFAULT_INLINE_OMITTED,
    },
  },
  [Scene.RoomsNumber]: {
    REG_EXP_PATTERN: /^[1-4]$/,
    ERROR_MESSAGE: {
      WRONG_VALUE: `Please specify value from <b>1</b> to <b>4</b>`,
      INLINE_OMITTED: DEFAULT_INLINE_OMITTED,
    },
  },
  [Scene.Price]: {
    REG_EXP_PATTERN: /^[1-9]\d{2,4}$/,
    ERROR_MESSAGE: {
      WRONG_VALUE: `Please specify value from <b>100</b> to <b>99999</b>`,
      MAX_CANT_BE_LESS_THAN_MIN: `Max <b>Price</b> can't be less that min!`,
      INLINE_OMITTED: DEFAULT_INLINE_OMITTED,
    },
  },
  [Scene.Private]: {
    ERROR_MESSAGE: {
      WRONG_VALUE: `Please choose <b>${BlitzResponse.Yes}</b> or <b>${BlitzResponse.No}</b>`,
    },
  },
}

export const SCENE_TO_TEXT_MAPPER: Record<Scene, ISceneText> = {
  [Scene.Area]: {
    [BotCommand.Start]: {
      MIN_AREA: `Please specify min <b>Area m²</b>:`,
      MAX_AREA: `Please specify max <b>Area m²</b>:`,
      INLINE_QUESTION: `Do you want to specify <b>Area m²</b>?`,
    },
    [BotCommand.Update]: {
      MIN_AREA: `Please update min <b>Area m²</b>:`,
      MAX_AREA: `Please update max <b>Area m²</b>:`,
      INLINE_QUESTION: `Do you want to update <b>Area m²</b>?`,
    },
  },
  [Scene.City]: {
    [BotCommand.Start]: {
      SELECT_CITY: `Please select <b>City</b>:`,
      INLINE_QUESTION: `Do you want to specify <b>City</b>?`,
    },
    [BotCommand.Update]: {
      SELECT_CITY: `Please select <b>City</b>:`,
      INLINE_QUESTION: `Do you want to update <b>City</b>?`,
    },
  },
  [Scene.Price]: {
    [BotCommand.Start]: {
      MIN_PRICE: `Please specify min <b>Price</b> (in PLN):`,
      MAX_PRICE: `Please specify max <b>Price</b> (in PLN):`,
      INLINE_QUESTION: `Do you want to specify <b>Price</b>?`,
    },
    [BotCommand.Update]: {
      MIN_PRICE: `Please update min <b>Price</b> (in PLN):`,
      MAX_PRICE: `Please update max <b>Price</b> (in PLN):`,
      INLINE_QUESTION: `Do you want to update <b>Price</b>?`,
    },
  },
  [Scene.Private]: {
    [BotCommand.Start]: {
      SHOULD_BE_PRIVATE: `Should advertisements be <b>Private</b>?`,
    },
    [BotCommand.Update]: {
      SHOULD_BE_PRIVATE: `Should advertisements be <b>Private</b>?`,
    },
  },
  [Scene.Province]: {
    [BotCommand.Start]: {
      INLINE_QUESTION: `Do you want to specify <b>Province</b>?`,
      HOW_PROVIDE_DETAILS: `How would you like to provide Province details?`,
      SELECT_PROVINCE: `Please select <b>Province</b>:`,
      LOCATION: 'Provide location',
      FROM_LIST: 'Provide Province from list',
      CURRENT_CITY: `Current city: `,
    },
    [BotCommand.Update]: {
      INLINE_QUESTION: `Do you want to update <b>Province</b>?`,
      HOW_PROVIDE_DETAILS: `How would you like to update Province details?`,
      SELECT_PROVINCE: `Please select <b>Province</b>:`,
      LOCATION: 'Update location',
      FROM_LIST: 'Update Province from list',
      CURRENT_CITY: `Current city: `,
    },
  },
  [Scene.RoomsNumber]: {
    [BotCommand.Start]: {
      ROOMS_NUMBER: `Please specify <b>Number of Rooms</b>:`,
      INLINE_QUESTION: `Do you want to specify <b>Number of Rooms</b>?`,
    },
    [BotCommand.Update]: {
      ROOMS_NUMBER: `Please update <b>Number of Rooms</b>:`,
      INLINE_QUESTION: `Do you want to update <b>Number of Rooms</b>?`,
    },
  },
};

export const PROVINCE_TO_CITY_MAPPER: {
  [key in Province]: City[];
} = {
  [Province.Dolnoslaskie]: [
    City.Bielawa,
    City.Bogatynia,
    City.BoguszowGorce,
    City.Boleslawiec,
    City.Dzierzoniow,
    City.Glogow,
    City.Jawor,
    City.JelczLaskowice,
    City.JeleniaGora,
    City.KamiennaGora,
    City.Klodzko,
    City.Legnica,
    City.Luban,
    City.Lubin,
    City.NowaRuda,
    City.Olawa,
    City.Olesnica,
    City.Polkowice,
    City.Strzegom,
    City.Swidnica,
    City.Swiebodzice,
    City.Walbrzych,
    City.Wroclaw,
    City.ZabkowiceSląskie,
    City.Zgorzelec,
    City.Zlotoryja,
  ],
  [Province.KujawskoPomorskie]: [
    City.Brodnica,
    City.Bydgoszcz,
    City.Chelmno,
    City.Grudziadz,
    City.Inowroclaw,
    City.NakloNadNotecia,
    City.Rypin,
    City.SolecKujawski,
    City.Swiecie,
    City.Torun,
    City.Wloclawek,
  ],
  [Province.Lubelskie]: [
    City.BialaPodlaska,
    City.Bilgoraj,
    City.Chelm,
    City.Deblin,
    City.Hrubieszow,
    City.Krasnik,
    City.Krasnystaw,
    City.Leczna,
    City.Lubartow,
    City.Lublin,
    City.Lukow,
    City.MiedzyrzecPodlaski,
    City.Pulawy,
    City.RadzynPodlaski,
    City.Swidnik,
    City.TomaszowLubelski,
    City.Zamosc,
  ],
  [Province.Lubuskie]: [
    City.GorzowWielkopolski,
    City.Gubin,
    City.KostrzynNadOdra,
    City.Miedzyrzecz,
    City.NowaSol,
    City.Slubice,
    City.Sulechow,
    City.Swiebodzin,
    City.Zagan,
    City.Zary,
    City.ZielonaGora,
  ],
  [Province.Lodzkie]: [
    City.AleksandrowLodzki,
    City.Belchatow,
    City.Glowno,
    City.KonstantynowLodzki,
    City.Kutno,
    City.Lask,
    City.Leczyca,
    City.Lodz,
    City.Lowicz,
    City.Opoczno,
    City.Ozorkow,
    City.Pabianice,
    City.PiotrkowTrybunalski,
    City.Radomsko,
    City.RawaMazowiecka,
    City.Sieradz,
    City.Skierniewice,
    City.TomaszowMazowiecki,
    City.Wielun,
    City.ZdunskaWola,
    City.Zgierz,
  ],
  [Province.Malopolskie]: [
    City.Andrychow,
    City.Bochnia,
    City.Brzesko,
    City.Chrzanow,
    City.Gorlice,
    City.Kety,
    City.Krakow,
    City.Libiaz,
    City.Limanowa,
    City.Myslenice,
    City.NowySacz,
    City.NowyTarg,
    City.Olkusz,
    City.Oswiecim,
    City.Skawina,
    City.Tarnow,
    City.Trzebinia,
    City.Wadowice,
    City.Wieliczka,
    City.Zakopane,
  ],
  [Province.Mazowieckie]: [
    City.Ciechanow,
    City.Garwolin,
    City.Gostynin,
    City.GrodziskMazowiecki,
    City.Grojec,
    City.Jozefow,
    City.Kobylka,
    City.KonstancinJeziorna,
    City.Kozienice,
    City.Legionowo,
    City.Lomianki,
    City.Marki,
    City.Milanowek,
    City.MinskMazowiecki,
    City.Mlawa,
    City.NowyDworMazowiecki,
    City.Ostrolęka,
    City.OstrowMazowiecka,
    City.Otwock,
    City.Piaseczno,
    City.Piastow,
    City.Pionki,
    City.Plock,
    City.Plonsk,
    City.Pruszkow,
    City.Przasnysz,
    City.Pultusk,
    City.Radom,
    City.Siedlce,
    City.Sierpc,
    City.Sochaczew,
    City.SokolowPodlaski,
    City.Sulejowek,
    City.Warszawa,
    City.Wolomin,
    City.Wyszkow,
    City.Zabki,
    City.Zielonka,
    City.Zyrardow,
  ],
  [Province.Opolskie]: [
    City.Brzeg,
    City.KedzierzynKozle,
    City.Kluczbork,
    City.Krapkowice,
    City.Namyslów,
    City.Nysa,
    City.Opole,
    City.Prudnik,
    City.StrzelceOpolskie,
  ],
  [Province.Podkarpackie]: [
    City.Debica,
    City.Jaroslaw,
    City.Jaslo,
    City.Krosno,
    City.Lancut,
    City.Mielec,
    City.Nisko,
    City.Przemysl,
    City.Przeworsk,
    City.Ropczyce,
    City.Rzeszow,
    City.Sanok,
    City.StalowaWola,
    City.Tarnobrzeg,
  ],
  [Province.Podlaskie]: [
    City.Augustow,
    City.Bialystok,
    City.BielskPodlaski,
    City.Grajewo,
    City.Hajnowka,
    City.Lapy,
    City.Lomza,
    City.Siemiatycze,
    City.Sokolka,
    City.Suwalki,
    City.Zambrow,
  ],
  [Province.Pomorskie]: [
    City.Bydgoszcz,
    City.Bytow,
    City.Chojnice,
    City.Gdansk,
    City.Gdynia,
    City.Kartuzy,
    City.Koscierzyna,
    City.Kwidzyn,
    City.Lebork,
    City.Malbork,
    City.PruszczGdanski,
    City.Reda,
    City.Rumia,
    City.Slupsk,
    City.Sopot,
    City.StarogardGdanski,
    City.Tczew,
    City.Ustka,
    City.Wejherow,
  ],
  [Province.Slaskie]: [
    City.Bedzin,
    City.BielskoBiala,
    City.Bierun,
    City.Bytom,
    City.Chorzow,
    City.Cieszyn,
    City.CzechowiceDziedzice,
    City.Czeladz,
    City.CzerwionkaLeszczyny,
    City.Czestochowa,
    City.DąbrowaGornicza,
    City.Gliwice,
    City.JastrzebieZdroj,
    City.Jaworzno,
    City.Katowice,
    City.Knurow,
    City.LaziskaGorne,
    City.Ledziny,
    City.Lubliniec,
    City.Mikolow,
    City.Myslowice,
    City.Myszkow,
    City.Orzesze,
    City.PiekarySlaskie,
    City.Pszczyna,
    City.Pyskowice,
    City.Raciborz,
    City.Radlin,
    City.Radzionkow,
    City.RudaSlaska,
    City.Rybnik,
    City.Rydultowy,
    City.SiemianowiceSlaskie,
    City.Sosnowiec,
    City.Swietochlowice,
    City.TarnowskieGory,
    City.Tychy,
    City.Ustron,
    City.WodzislawSlaski,
    City.Zabrze,
    City.Zawiercie,
    City.Zory,
    City.Zywiec,
  ],
  [Province.Swietokrzyskie]: [
    City.BuskoZdroj,
    City.Jedrzejow,
    City.Kielce,
    City.Konskie,
    City.OstrowiecSwietokrzyski,
    City.Sandomierz,
    City.SkarzyskoKamienna,
    City.Starachowice,
    City.Staszow,
  ],
  [Province.WarminskoMazurskie]: [
    City.Bartoszyce,
    City.Braniewo,
    City.Dzialdowo,
    City.Elbląg,
    City.Elk,
    City.Gizycko,
    City.Ilawa,
    City.Ketrzyn,
    City.LidzbarkWarminski,
    City.Mragowo,
    City.Olecko,
    City.Olsztyn,
    City.Ostroda,
    City.Pisz,
    City.Szczytno,
  ],
  [Province.Wielkopolskie]: [
    City.Chodziez,
    City.Gniezno,
    City.Gostyn,
    City.Jarocin,
    City.Kalisz,
    City.Kolo,
    City.Konin,
    City.Koscian,
    City.Krotoszyn,
    City.Leszno,
    City.Lubon,
    City.NowyTomysl,
    City.Oborniki,
    City.OstrowWielkopolski,
    City.Pila,
    City.Pleszew,
    City.Poznan,
    City.Rawicz,
    City.Srem,
    City.SrodaWielkopolska,
    City.Swarzedz,
    City.Szamotuly,
    City.Trzcianka,
    City.Turek,
    City.Wągrowiec,
    City.Wrzesnia,
    City.Zlotow,
  ],
  [Province.Zachodniopomorskie]: [
    City.Bialogard,
    City.Choszczno,
    City.Goleniow,
    City.Gryfice,
    City.Gryfino,
    City.KamienPomorski,
    City.Kolobrzeg,
    City.Koszalin,
    City.Nowogard,
    City.Police,
    City.Stargard,
    City.Swidwin,
    City.Swinoujscie,
    City.Szczecin,
    City.Szczecinek,
    City.Walcz,
  ],
};
