import type { User as ITelegramUser } from 'typegram';
import { IUser, ICriteria } from '../models';
import { Province, City } from './models';

export const mapTelegramUserToUser = (
  telegramUser: ITelegramUser,
  criteria: ICriteria,
): IUser => {
  const newUser: IUser = {
    telegramId: telegramUser.id,
    isBot: telegramUser.is_bot,
    firstName: telegramUser.first_name,
    lastName: telegramUser.last_name,
    nickname: telegramUser.username,
    languageCode: telegramUser.language_code,
    criteria: { ...criteria },
  };

  return newUser;
};

export const PROVINCE_TO_CITY_MAPPER: {
  [key in Province]: City[];
} = {
  [Province.Dolnoslaskie]: [
    City.Bielawa,
    City.Bogatynia,
    City.BoguszowGorce,
    City.Boleslawiec,
    City.Dzierzoniow,
    City.Glogow,
    City.Jawor,
    City.JelczLaskowice,
    City.JeleniaGora,
    City.KamiennaGora,
    City.Klodzko,
    City.Legnica,
    City.Luban,
    City.Lubin,
    City.NowaRuda,
    City.Olawa,
    City.Olesnica,
    City.Polkowice,
    City.Strzegom,
    City.Swidnica,
    City.Swiebodzice,
    City.Walbrzych,
    City.Wroclaw,
    City.ZabkowiceSląskie,
    City.Zgorzelec,
    City.Zlotoryja,
  ],
  [Province.KujawskoPomorskie]: [
    City.Brodnica,
    City.Bydgoszcz,
    City.Chelmno,
    City.Grudziadz,
    City.Inowroclaw,
    City.NakloNadNotecia,
    City.Rypin,
    City.SolecKujawski,
    City.Swiecie,
    City.Torun,
    City.Wloclawek,
  ],
  [Province.Lubelskie]: [
    City.BialaPodlaska,
    City.Bilgoraj,
    City.Chelm,
    City.Deblin,
    City.Hrubieszow,
    City.Krasnik,
    City.Krasnystaw,
    City.Leczna,
    City.Lubartow,
    City.Lublin,
    City.Lukow,
    City.MiedzyrzecPodlaski,
    City.Pulawy,
    City.RadzynPodlaski,
    City.Swidnik,
    City.TomaszowLubelski,
    City.Zamosc,
  ],
  [Province.Lubuskie]: [
    City.GorzowWielkopolski,
    City.Gubin,
    City.KostrzynNadOdra,
    City.Miedzyrzecz,
    City.NowaSol,
    City.Slubice,
    City.Sulechow,
    City.Swiebodzin,
    City.Zagan,
    City.Zary,
    City.ZielonaGora,
  ],
  [Province.Lodzkie]: [
    City.AleksandrowLodzki,
    City.Belchatow,
    City.Glowno,
    City.KonstantynowLodzki,
    City.Kutno,
    City.Lask,
    City.Leczyca,
    City.Lodz,
    City.Lowicz,
    City.Opoczno,
    City.Ozorkow,
    City.Pabianice,
    City.PiotrkowTrybunalski,
    City.Radomsko,
    City.RawaMazowiecka,
    City.Sieradz,
    City.Skierniewice,
    City.TomaszowMazowiecki,
    City.Wielun,
    City.ZdunskaWola,
    City.Zgierz,
  ],
  [Province.Malopolskie]: [
    City.Andrychow,
    City.Bochnia,
    City.Brzesko,
    City.Chrzanow,
    City.Gorlice,
    City.Kety,
    City.Krakow,
    City.Libiaz,
    City.Limanowa,
    City.Myslenice,
    City.NowySacz,
    City.NowyTarg,
    City.Olkusz,
    City.Oswiecim,
    City.Skawina,
    City.Tarnow,
    City.Trzebinia,
    City.Wadowice,
    City.Wieliczka,
    City.Zakopane,
  ],
  [Province.Mazowieckie]: [
    City.Ciechanow,
    City.Garwolin,
    City.Gostynin,
    City.GrodziskMazowiecki,
    City.Grojec,
    City.Jozefow,
    City.Kobylka,
    City.KonstancinJeziorna,
    City.Kozienice,
    City.Legionowo,
    City.Lomianki,
    City.Marki,
    City.Milanowek,
    City.MinskMazowiecki,
    City.Mlawa,
    City.NowyDworMazowiecki,
    City.Ostrolęka,
    City.OstrowMazowiecka,
    City.Otwock,
    City.Piaseczno,
    City.Piastow,
    City.Pionki,
    City.Plock,
    City.Plonsk,
    City.Pruszkow,
    City.Przasnysz,
    City.Pultusk,
    City.Radom,
    City.Siedlce,
    City.Sierpc,
    City.Sochaczew,
    City.SokolowPodlaski,
    City.Sulejowek,
    City.Warszawa,
    City.Wolomin,
    City.Wyszkow,
    City.Zabki,
    City.Zielonka,
    City.Zyrardow,
  ],
  [Province.Opolskie]: [
    City.Brzeg,
    City.KedzierzynKozle,
    City.Kluczbork,
    City.Krapkowice,
    City.Namyslów,
    City.Nysa,
    City.Opole,
    City.Prudnik,
    City.StrzelceOpolskie,
  ],
  [Province.Podkarpackie]: [
    City.Debica,
    City.Jaroslaw,
    City.Jaslo,
    City.Krosno,
    City.Lancut,
    City.Mielec,
    City.Nisko,
    City.Przemysl,
    City.Przeworsk,
    City.Ropczyce,
    City.Rzeszow,
    City.Sanok,
    City.StalowaWola,
    City.Tarnobrzeg,
  ],
  [Province.Podlaskie]: [
    City.Augustow,
    City.Bialystok,
    City.BielskPodlaski,
    City.Grajewo,
    City.Hajnowka,
    City.Lapy,
    City.Lomza,
    City.Siemiatycze,
    City.Sokolka,
    City.Suwalki,
    City.Zambrow,
  ],
  [Province.Pomorskie]: [
    City.Bydgoszcz,
    City.Bytow,
    City.Chojnice,
    City.Gdansk,
    City.Gdynia,
    City.Kartuzy,
    City.Koscierzyna,
    City.Kwidzyn,
    City.Lebork,
    City.Malbork,
    City.PruszczGdanski,
    City.Reda,
    City.Rumia,
    City.Slupsk,
    City.Sopot,
    City.StarogardGdanski,
    City.Tczew,
    City.Ustka,
    City.Wejherow,
  ],
  [Province.Slaskie]: [
    City.Bedzin,
    City.BielskoBiala,
    City.Bierun,
    City.Bytom,
    City.Chorzow,
    City.Cieszyn,
    City.CzechowiceDziedzice,
    City.Czeladz,
    City.CzerwionkaLeszczyny,
    City.Czestochowa,
    City.DąbrowaGornicza,
    City.Gliwice,
    City.JastrzebieZdroj,
    City.Jaworzno,
    City.Katowice,
    City.Knurow,
    City.LaziskaGorne,
    City.Ledziny,
    City.Lubliniec,
    City.Mikolow,
    City.Myslowice,
    City.Myszkow,
    City.Orzesze,
    City.PiekarySlaskie,
    City.Pszczyna,
    City.Pyskowice,
    City.Raciborz,
    City.Radlin,
    City.Radzionkow,
    City.RudaSlaska,
    City.Rybnik,
    City.Rydultowy,
    City.SiemianowiceSlaskie,
    City.Sosnowiec,
    City.Swietochlowice,
    City.TarnowskieGory,
    City.Tychy,
    City.Ustron,
    City.WodzislawSlaski,
    City.Zabrze,
    City.Zawiercie,
    City.Zory,
    City.Zywiec,
  ],
  [Province.Swietokrzyskie]: [
    City.BuskoZdroj,
    City.Jedrzejow,
    City.Kielce,
    City.Konskie,
    City.OstrowiecSwietokrzyski,
    City.Sandomierz,
    City.SkarzyskoKamienna,
    City.Starachowice,
    City.Staszow,
  ],
  [Province.WarminskoMazurskie]: [
    City.Bartoszyce,
    City.Braniewo,
    City.Dzialdowo,
    City.Elbląg,
    City.Elk,
    City.Gizycko,
    City.Ilawa,
    City.Ketrzyn,
    City.LidzbarkWarminski,
    City.Mragowo,
    City.Olecko,
    City.Olsztyn,
    City.Ostroda,
    City.Pisz,
    City.Szczytno,
  ],
  [Province.Wielkopolskie]: [
    City.Chodziez,
    City.Gniezno,
    City.Gostyn,
    City.Jarocin,
    City.Kalisz,
    City.Kolo,
    City.Konin,
    City.Koscian,
    City.Krotoszyn,
    City.Leszno,
    City.Lubon,
    City.NowyTomysl,
    City.Oborniki,
    City.OstrowWielkopolski,
    City.Pila,
    City.Pleszew,
    City.Poznan,
    City.Rawicz,
    City.Srem,
    City.SrodaWielkopolska,
    City.Swarzedz,
    City.Szamotuly,
    City.Trzcianka,
    City.Turek,
    City.Wągrowiec,
    City.Wrzesnia,
    City.Zlotow,
  ],
  [Province.Zachodniopomorskie]: [
    City.Bialogard,
    City.Choszczno,
    City.Goleniow,
    City.Gryfice,
    City.Gryfino,
    City.KamienPomorski,
    City.Kolobrzeg,
    City.Koszalin,
    City.Nowogard,
    City.Police,
    City.Stargard,
    City.Swidwin,
    City.Swinoujscie,
    City.Szczecin,
    City.Szczecinek,
    City.Walcz,
  ],
};
