import { Schema, model } from 'mongoose';
import type { Document } from 'mongoose';

export enum Province {
  Dolnoslaskie = 'Dolnośląskie',
  KujawskoPomorskie = 'Kujawsko-pomorskie',
  Lubelskie = 'Lubelskie',
  Lubuskie = 'Lubuskie',
  Lodzkie = 'Łódzkie',
  Malopolskie = 'Małopolskie',
  Mazowieckie = 'Mazowieckie',
  Opolskie = 'Opolskie',
  Podkarpackie = 'Podkarpackie',
  Podlaskie = 'Podlaskie',
  Pomorskie = 'Pomorskie',
  Slaskie = 'Śląskie',
  Swietokrzyskie = 'Świętokrzyskie',
  WarminskoMazurskie = 'Warmińsko-mazurskie',
  Wielkopolskie = 'Wielkopolskie',
  Zachodniopomorskie = 'Zachodniopomorskie',
}

export enum City {
  Bielawa = 'Bielawa',
  Bogatynia = 'Bogatynia',
  BoguszowGorce = 'Boguszów-Gorce',
  Boleslawiec = 'Bolesławiec',
  Dzierzoniow = 'Dzierżoniów',
  Glogow = 'Głogów',
  Jawor = 'Jawor',
  JelczLaskowice = 'Jelcz-Laskowice',
  JeleniaGora = 'Jelenia Góra',
  KamiennaGora = 'Kamienna Góra',
  Klodzko = 'Kłodzko',
  Legnica = 'Legnica',
  Luban = 'Lubań',
  Lubin = 'Lubin',
  NowaRuda = 'Nowa Ruda',
  Olawa = 'Oława',
  Olesnica = 'Oleśnica',
  Polkowice = 'Polkowice',
  Strzegom = 'Strzegom',
  Swidnica = 'Świdnica',
  Swiebodzice = 'Świebodzice',
  Walbrzych = 'Wałbrzych',
  Wroclaw = 'Wrocław',
  ZabkowiceSląskie = 'Ząbkowice Śląskie',
  Zgorzelec = 'Zgorzelec',
  Zlotoryja = 'Złotoryja',

  Brodnica = 'Brodnica',
  Bydgoszcz = 'Bydgoszcz',
  Chelmno = 'Chełmno',
  Grudziadz = 'Grudziądz',
  Inowroclaw = 'Inowrocław',
  NakloNadNotecia = 'Nakło nad Notecią',
  Rypin = 'Rypin',
  SolecKujawski = 'Solec Kujawski',
  Swiecie = 'Świecie',
  Torun = 'Toruń',
  Wloclawek = 'Włocławek',

  BialaPodlaska = 'Biała Podlaska',
  Bilgoraj = 'Biłgoraj',
  Chelm = 'Chełm',
  Deblin = 'Dęblin',
  Hrubieszow = 'Hrubieszów',
  Krasnik = 'Kraśnik',
  Krasnystaw = 'Krasnystaw',
  Leczna = 'Łęczna',
  Lubartow = 'Lubartów',
  Lublin = 'Lublin',
  Lukow = 'Łuków',
  MiedzyrzecPodlaski = 'Międzyrzec Podlaski',
  Pulawy = 'Puławy',
  RadzynPodlaski = 'Radzyń Podlaski',
  Swidnik = 'Świdnik',
  TomaszowLubelski = 'Tomaszów Lubelski',
  Zamosc = 'Zamość',

  GorzowWielkopolski = 'Gorzów Wielkopolski',
  Gubin = 'Gubin',
  KostrzynNadOdra = 'Kostrzyn nad Odrą',
  Miedzyrzecz = 'Międzyrzecz',
  NowaSol = 'Nowa Sól',
  Slubice = 'Słubice',
  Sulechow = 'Sulechów',
  Swiebodzin = 'Świebodzin',
  Zagan = 'Żagań',
  Zary = 'Żary',
  ZielonaGora = 'Zielona Góra',

  AleksandrowLodzki = "Aleksandrów Łódzki",
  Belchatow = "Bełchatów",
  Glowno = "Głowno",
  KonstantynowLodzki = "Konstantynów Łódzki",
  Kutno = "Kutno",
  Lask = "Łask",
  Leczyca = "Łęczyca",
  Lodz = "Łódź",
  Lowicz = "Łowicz",
  Opoczno = "Opoczno",
  Ozorkow = "Ozorków",
  Pabianice = "Pabianice",
  PiotrkowTrybunalski = "Piotrków Trybunalski",
  Radomsko = "Radomsko",
  RawaMazowiecka = "Rawa Mazowiecka",
  Sieradz = "Sieradz",
  Skierniewice = "Skierniewice",
  TomaszowMazowiecki = "Tomaszów Mazowiecki",
  Wielun = "Wieluń",
  ZdunskaWola = "Zduńska Wola",
  Zgierz = "Zgierz",

  Andrychow = "Andrychów",
  Bochnia = "Bochnia",
  Brzesko = "Brzesko",
  Chrzanow = "Chrzanów",
  Gorlice = "Gorlice",
  Kety = "Kęty",
  Krakow = "Kraków",
  Libiaz = "Libiąż",
  Limanowa = "Limanowa",
  Myslenice = "Myślenice",
  NowySacz = "Nowy Sącz",
  NowyTarg = "Nowy Targ",
  Olkusz = "Olkusz",
  Oswiecim = "Oświęcim",
  Skawina = "Skawina",
  Tarnow = "Tarnów",
  Trzebinia = "Trzebinia",
  Wadowice = "Wadowice",
  Wieliczka = "Wieliczka",
  Zakopane = "Zakopane",

  Ciechanow = "Ciechanów",
  Garwolin = "Garwolin",
  Gostynin = "Gostynin",
  GrodziskMazowiecki = "Grodzisk Mazowiecki",
  Grojec = "Grójec",
  Jozefow = "Józefów",
  Kobylka = "Kobyłka",
  KonstancinJeziorna = "Konstancin-Jeziorna",
  Kozienice = "Kozienice",
  Legionowo = "Legionowo",
  Lomianki = "Łomianki",
  Marki = "Marki",
  Milanowek = "Milanówek",
  MinskMazowiecki = "Mińsk Mazowiecki",
  Mlawa = "Mława",
  NowyDworMazowiecki = "Nowy Dwór Mazowiecki",
  Ostrolęka = "Ostrołęka",
  OstrowMazowiecka = "Ostrów Mazowiecka",
  Otwock = "Otwock",
  Piaseczno = "Piaseczno",
  Piastow = "Piastów",
  Pionki = "Pionki",
  Plock = "Płock",
  Plonsk = "Płońsk",
  Pruszkow = "Pruszków",
  Przasnysz = "Przasnysz",
  Pultusk = "Pułtusk",
  Radom = "Radom",
  Siedlce = "Siedlce",
  Sierpc = "Sierpc",
  Sochaczew = "Sochaczew",
  SokolowPodlaski = "Sokołów Podlaski",
  Sulejowek = "Sulejówek",
  Warszawa = "Warszawa",
  Wolomin = "Wołomin",
  Wyszkow = "Wyszków",
  Zabki = "Ząbki",
  Zielonka = "Zielonka",
  Zyrardow = "Żyrardów",

  Brzeg = "Brzeg",
  KedzierzynKozle = "Kędzierzyn-Koźle",
  Kluczbork = "Kluczbork",
  Krapkowice = "Krapkowice",
  Namyslów = "Namysłów",
  Nysa = "Nysa",
  Opole = "Opole",
  Prudnik = "Prudnik",
  StrzelceOpolskie = "Strzelce Opolskie",

  Debica = "Dębica",
  Jaroslaw = "Jarosław",
  Jaslo = "Jasło",
  Krosno = "Krosno",
  Lancut = "Łańcut",
  Mielec = "Mielec",
  Nisko = "Nisko",
  Przemysl = "Przemyśl",
  Przeworsk = "Przeworsk",
  Ropczyce = "Ropczyce",
  Rzeszow = "Rzeszów",
  Sanok = "Sanok",
  StalowaWola = "Stalowa Wola",
  Tarnobrzeg = "Tarnobrzeg",

  Augustow = "Augustów",
  Bialystok = "Białystok",
  BielskPodlaski = "Bielsk Podlaski",
  Grajewo = "Grajewo",
  Hajnowka = "Hajnówka",
  Lapy = "Łapy",
  Lomza = "Łomża",
  Siemiatycze = "Siemiatycze",
  Sokolka = "Sokółka",
  Suwalki = "Suwałki",
  Zambrow = "Zambrów",

  // Bydgoszcz = "Bydgoszcz",
  Bytow = "Bytów",
  Chojnice = "Chojnice",
  Gdansk = "Gdańsk",
  Gdynia = "Gdynia",
  Kartuzy = "Kartuzy",
  Koscierzyna = "Kościerzyna",
  Kwidzyn = "Kwidzyn",
  Lebork = "Lębork",
  Malbork = "Malbork",
  PruszczGdanski = "Pruszcz Gdański",
  Reda = "Reda",
  Rumia = "Rumia",
  Slupsk = "Słupsk",
  Sopot = "Sopot",
  StarogardGdanski = "Starogard Gdański",
  Tczew = "Tczew",
  Ustka = "Ustka",
  Wejherow = "Wejherowo",

  Bedzin = "Będzin",
  BielskoBiala = "Bielsko-Biała",
  Bierun = "Bieruń",
  Bytom = "Bytom",
  Chorzow = "Chorzów",
  Cieszyn = "Cieszyn",
  CzechowiceDziedzice = "Czechowice-Dziedzice",
  Czeladz = "Czeladź",
  CzerwionkaLeszczyny = "Czerwionka-Leszczyny",
  Czestochowa = "Częstochowa",
  DąbrowaGornicza = "Dąbrowa Górnicza",
  Gliwice = "Gliwice",
  JastrzebieZdroj = "Jastrzębie-Zdrój",
  Jaworzno = "Jaworzno",
  Katowice = "Katowice",
  Knurow = "Knurów",
  LaziskaGorne = "Łaziska Górne",
  Ledziny = "Lędziny",
  Lubliniec = "Lubliniec",
  Mikolow = "Mikołów",
  Myslowice = "Mysłowice",
  Myszkow = "Myszków",
  Orzesze = "Orzesze",
  PiekarySlaskie = "Piekary Śląskie",
  Pszczyna = "Pszczyna",
  Pyskowice = "Pyskowice",
  Raciborz = "Racibórz",
  Radlin = "Radlin",
  Radzionkow = "Radzionków",
  RudaSlaska = "Ruda Śląska",
  Rybnik = "Rybnik",
  Rydultowy = "Rydułtowy",
  SiemianowiceSlaskie = "Siemianowice Śląskie",
  Sosnowiec = "Sosnowiec",
  Swietochlowice = "Świętochłowice",
  TarnowskieGory = "Tarnowskie Góry",
  Tychy = "Tychy",
  Ustron = "Ustroń",
  WodzislawSlaski = "Wodzisław Śląski",
  Zabrze = "Zabrze",
  Zawiercie = "Zawiercie",
  Zory = "Żory",
  Zywiec = "Żywiec",

  BuskoZdroj = "Busko-Zdrój",
  Jedrzejow = "Jędrzejów",
  Kielce = "Kielce",
  Konskie = "Końskie",
  OstrowiecSwietokrzyski = "Ostrowiec Świętokrzyski",
  Sandomierz = "Sandomierz",
  SkarzyskoKamienna = "Skarżysko-Kamienna",
  Starachowice = "Starachowice",
  Staszow = "Staszów",

  Bartoszyce = "Bartoszyce",
  Braniewo = "Braniewo",
  Dzialdowo = "Działdowo",
  Elbląg = "Elbląg",
  Elk = "Ełk",
  Gizycko = "Giżycko",
  Ilawa = "Iława",
  Ketrzyn = "Kętrzyn",
  LidzbarkWarminski = "Lidzbark Warmiński",
  Mragowo = "Mrągowo",
  Olecko = "Olecko",
  Olsztyn = "Olsztyn",
  Ostroda = "Ostróda",
  Pisz = "Pisz",
  Szczytno = "Szczytno",

  Chodziez = "Chodzież",
  Gniezno = "Gniezno",
  Gostyn = "Gostyń",
  Jarocin = "Jarocin",
  Kalisz = "Kalisz",
  Kolo = "Koło",
  Konin = "Konin",
  Koscian = "Kościan",
  Krotoszyn = "Krotoszyn",
  Leszno = "Leszno",
  Lubon = "Luboń",
  NowyTomysl = "Nowy Tomyśl",
  Oborniki = "Oborniki",
  OstrowWielkopolski = "Ostrów Wielkopolski",
  Pila = "Piła",
  Pleszew = "Pleszew",
  Poznan = "Poznań",
  Rawicz = "Rawicz",
  Srem = "Śrem",
  SrodaWielkopolska = "Środa Wielkopolska",
  Swarzedz = "Swarzędz",
  Szamotuly = "Szamotuły",
  Trzcianka = "Trzcianka",
  Turek = "Turek",
  Wągrowiec = "Wągrowiec",
  Wrzesnia = "Września",
  Zlotow = "Złotów",

  Bialogard = "Białogard",
  Choszczno = "Choszczno",
  Goleniow = "Goleniów",
  Gryfice = "Gryfice",
  Gryfino = "Gryfino",
  KamienPomorski = "Kamień Pomorski",
  Kolobrzeg = "Kołobrzeg",
  Koszalin = "Koszalin",
  Nowogard = "Nowogard",
  Police = "Police",
  Stargard = "Stargard",
  Swidwin = "Świdwin",
  Swinoujscie = "Świnoujście",
  Szczecin = "Szczecin",
  Szczecinek = "Szczecinek",
  Walcz = "Wałcz",
}

export interface ICriteria {
  roomsNumber?: number;
  priceMin?: number;
  priceMax?: number;
  areaMin?: number;
  areaMax?: number;
  province?: Province;
  city?: City;
  isPrivate: boolean;
};

export interface IUser {
  telegramId: number;
  isBot: boolean;
  firstName: string;
  lastName?: string;
  nickname?: string;
  languageCode?: string;
  criteria: ICriteria;
  isActive: boolean;
};

export interface IUserDocument extends IUser, Document {
  createdAt: Date;
  updatedAt: Date;
};

const criteriaSchema = new Schema<ICriteria>({
  roomsNumber: Number,
  priceMin: Number,
  priceMax: Number,
  areaMin: Number,
  areaMax: Number,
  province: {
    type: String,
    enum: Province,
  },
  city: {
    type: String,
    enum: City,
  },
  isPrivate: {
    type: Boolean,
    required: true,
  },
}, { _id: false });

const userSchema = new Schema<IUserDocument>({
  telegramId: {
    type: Number,
    unique: true,
    index: true,
    required: true,
  },
  isBot: {
    type: Boolean,
    required: true,
  },
  firstName: {
    type: String,
    required: true,
  },
  lastName: String,
  nickname: {
    type: String,
    unique: true,
  },
  languageCode: String,
  criteria: criteriaSchema,
  isActive: {
    type: Boolean,
    required: true,
  },
}, { timestamps: true })

export const User = model<IUserDocument>('User', userSchema);
